name: Run linters

on:
    push:
        branches:
        - master

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Disable SSL verification for internal Gitea repo
              run: |
                git config --global http."https://gitea.homelab.com/".sslVerify false
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Set up .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: "8.0.x"
            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                auto_fix: true
                dotnet_format: true
                dotnet_format_auto_fix: true